### ISSUE TITLE
MariaDB-Shell-23.03.2.mac.x86_64.pkg is broken

### ISSUE THREAD

**Issue by subedinfo-it** [MariaDB/mariadb.org-tools#178]
Hi there,

So I proceeded to install mariadb-shell for macOS, [following MariaDB's instructions](https://mariadb.com/docs/skysql-previous-release/connect/clients/mariadb-shell/) downloaded from [mariadb's downloads](https://dlm.mariadb.com/browse/shell/255/1717/mac/) and installed.

When running `mariadb-shell`, I get the following:
```
 % mariadb-shell
Traceback (most recent call last):
  File "/Users/lizardo/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 131, in run
  File "/Users/lizardo/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
  File "sealion/__main__.py", line 5, in <module>
  File "/Users/lizardo/workspace/sealion/sealion/app.py", line 14, in <module>
  File "/Users/lizardo/workspace/sealion/sealion/commands.py", line 9, in <module>
  File "/Users/lizardo/.pyenv/versions/3.10.10/lib/python3.10/site-packages/mariadb/__init__.py", line 7, in <module>
ImportError: dlopen(/Library/MariaDB/shell/lib/mariadb/_mariadb.cpython-310-darwin.so, 0x0002): Library not loaded: '/usr/local/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.1.1.dylib'
  Referenced from: '/Library/MariaDB/shell/libssl.1.1.dylib'
  Reason: tried: '/usr/local/Cellar/openssl@1.1/1.1.1t/lib/libcrypto.1.1.dylib' (no such file), '/usr/lib/libcrypto.1.1.dylib' (no such file)
```

There's no `/Users/lizardo/` nor any `/usr/local/Cellar` nor `/usr/lib/libcrypto.1.1.dylib` - there isn't, in fact, such file.
There is, however, a `libcrypto.1.1.dylib` that was supplied by your package and put into `/Library/MariaDB/shell/libcrypto.1.1.dylib`.

I could link /usr/lib/xpto to the provided library, but I'll use another machine until a fix is released. Thank you.

**Comment by subedinfo-it** [comment]
[Reported on JIRA](https://jira.mariadb.org/browse/TOOLS-67)
